#!/bin/sh
# shellcheck disable=SC2068,SC2140

FIFO_PATH="${BOBBIT_FIFO_PATH:-./bobbitd.fifo}"
DATA_DIR="${BOBBIT_DATA_DIR:-./bobbitd}"
SEPARATOR="---"

remove_fifo() {
    rm -f "$FIFO_PATH"
    exit 0
}

trap remove_fifo INT
trap remove_fifo TERM

mkdir -p "$(dirname "$FIFO_PATH")"
rm -f "$FIFO_PATH"
mkfifo "$FIFO_PATH"
mkdir -p "$DATA_DIR"

echo "data dir: $DATA_DIR"
echo "fifo_path: $FIFO_PATH"

while read -r JOB < "$FIFO_PATH"; do
    case "$JOB" in
        *"$SEPARATOR"*)
        job_id="$(echo "$JOB" | sed "s/$SEPARATOR.*//")"
        job_command="$(echo "$JOB" | sed "s/.*$SEPARATOR//")"
        job_timestamp="$(date "+%D %H:%M:%S")"
        echo "timestamp: $job_timestamp, job: $job_id, command: $job_command"
        env PS4="${job_id}: " sh -xc "
            rm -f $DATA_DIR/${job_id}.exitcode $DATA_DIR/${job_id}.lock;
            touch $DATA_DIR/${job_id}.lock;
            env JOB_ID=${job_id} ${job_command} > $DATA_DIR/${job_id}.log 2>&1;
            echo \$? > $DATA_DIR/${job_id}.exitcode;
            rm $DATA_DIR/${job_id}.lock;
        " &
        ;;
    esac        
done
